import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { gallery, reviews } from '@/data/restaurant';
export function Gallery() {
 const [category,setCategory]=useState('All');const [selected,setSelected]=useState<number|null>(null);
 const shown=gallery.filter(item=>category==='All'||item.category===category);
 const change=(delta:number)=>setSelected(current=>current===null?null:(current+delta+gallery.length)%gallery.length);
 useEffect(()=>{if(selected===null)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setSelected(current=>current===null?null:(current+1)%gallery.length);if(e.key==='ArrowLeft')setSelected(current=>current===null?null:(current-1+gallery.length)%gallery.length);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected]);
 const current=selected===null?null:gallery[selected];
 return <><section className="gallery-section section-wrap" id="gallery"><div className="section-heading"><div><p className="eyebrow">Through our lens</p><h2 className="section-title">Moments worth <em>keeping.</em></h2></div><div className="gallery-filters">{['All','Food','Interior','Chef','Dining','Atmosphere'].map(cat=><Button key={cat} variant="editorial" aria-pressed={category===cat} className={category===cat?'active':''} onClick={()=>setCategory(cat)}>{cat}</Button>)}</div></div><div className="gallery-grid">{shown.map(item=><Button variant="editorial" className="signature-image-button" key={item.title} aria-label={`View ${item.title}`} onClick={()=>setSelected(gallery.indexOf(item))}><img src={item.image} alt={item.title} loading="lazy" width="1024" height="1024"/></Button>)}</div></section>
 <Dialog open={selected!==null} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="dining-dialog gallery-viewer"><DialogTitle className="sr-only">{current?.title??'Gallery'}</DialogTitle><DialogDescription className="sr-only">NOIRÉ photographs</DialogDescription>{current&&<><img src={current.image} alt={current.title}/><div className="gallery-viewer-controls"><Button variant="editorial" size="icon" aria-label="Previous photograph" onClick={()=>change(-1)}><ArrowLeft/></Button><p>{current.title} · {(selected??0)+1} / {gallery.length}</p><Button variant="editorial" size="icon" aria-label="Next photograph" onClick={()=>change(1)}><ArrowRight/></Button></div></>}</DialogContent></Dialog></>;
}
export function Reviews(){const [index,setIndex]=useState(0);const review=reviews[index];if(!review)return null;return <section className="reviews"><p className="eyebrow">The moments that stay / ★ ★ ★ ★ ★</p><blockquote className="review-quote">“{review.quote}”</blockquote><p className="review-author">{review.name} · {review.date}</p><div className="review-controls"><Button variant="editorial" size="icon" aria-label="Previous review" onClick={()=>setIndex((index-1+reviews.length)%reviews.length)}><ArrowLeft/></Button><span>0{index+1} / 0{reviews.length}</span><Button variant="editorial" size="icon" aria-label="Next review" onClick={()=>setIndex((index+1)%reviews.length)}><ArrowRight/></Button></div></section>;}